=== yousef8/iti-xml/lab1/lab1.dtd
<!ELEMENT library (location,description,librarian,books)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>
<!ELEMENT books (book+)>
<!ELEMENT book (title,author,preface,parts)>
<!ATTLIST book isbn CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT parts (part+)>
<!ELEMENT part (title,chapter+)>
<!ELEMENT chapter (title,summary,section+)>
<!ELEMENT section (paragraph+)>
<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT summary (#PCDATA)>

<!ATTLIST book category CDATA #IMPLIED>
<!ATTLIST author gender (male|female) "male">

<!ENTITY secret SYSTEM "secret.ent">

=== yousef8/iti-xml/lab1/lab1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE library SYSTEM "lab1.dtd">
<library>
    <location>
        53, cairo, egypt
    </location>
    <description>
        Huge library
    </description>
    <librarian>
        Omar
    </librarian>
    <books>
        <book isbn="34309487">
            <title>it</title>
            <author>Steven King</author>
            <preface>Preface</preface>
            <parts>
                <part>
                    <title>part 1</title>
                    <chapter>
                        <title>Chapter 1</title>
                        <summary>
                            chapter summary
                        </summary>
                        <section>
                            <paragraph>para 1</paragraph>
                            <paragraph>para 2</paragraph>
                            <paragraph>para 3</paragraph>
                        </section>
                    </chapter>
                    <chapter>
                        <title>Chapter 2</title>
                        <summary>
                            chapter summary
                        </summary>
                        <section>
                            <paragraph>para 1</paragraph>
                            <paragraph>para 2</paragraph>
                            <paragraph>para 3</paragraph>
                        </section>
                    </chapter>
                </part>
            </parts>
        </book>

        <book isbn="12343" category="Horror">
            <title>it</title>
            <author gender="male">Steven King</author>
            <preface>Preface</preface>
            <parts>
                <part>
                    <title>part 1 &secret;</title>
                    <chapter>
                        <title>Chapter 1</title>
                        <summary>
                            chapter summary
                        </summary>
                        <section>
                            <paragraph>para 1</paragraph>
                            <paragraph>para 2</paragraph>
                            <paragraph>para 3</paragraph>
                        </section>
                        <section>
                            <paragraph>para 1</paragraph>
                            <paragraph>para 2</paragraph>
                            <paragraph>para 3</paragraph>
                        </section>
                    </chapter>
                    <chapter>
                        <title>Chapter 2</title>
                        <summary>
                            chapter summary
                        </summary>
                        <section>
                            <paragraph>para 1</paragraph>
                            <paragraph>para 2</paragraph>
                            <paragraph>para 3</paragraph>
                        </section>
                    </chapter>
                </part>
            </parts>
        </book>
    </books>

</library>
